chapter_06/community_project/community_project/urls.py
from django.contrib import admin
from django.urls import path, include
from snsapp import views
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name="home"),
    path('postcreate', views.postcreate, name="postcreate"),
    path('detail/<int:post_id>', views.detail, name="detail"),
    path("create_comment/<int:post_id>", views.create_comment, name="create_comment"),

    path("login", accounts_views.login, name="login"),
    path("logout", accounts_views.logout, name="logout"),
    path("register", accounts_views.register, name="register"),
    

    path('idHome', views.idHome, name="idHome"),
    path('idPostcreate', views.idPostcreate, name="idPostcreate"),
    path("idDetail/<int:post_id>", views.idDetail, name="idDetail"),
    path("new_idComment/<int:post_id>", views.new_idComment, name="new_idComment"),

    path("accounts/", include('allauth.urls')),
]

chapter_06/community_project/snsapp/models.py
from django.db import models
from django.contrib.auth.models import User

# 게시글 모델(익명게시판)
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# 댓글 모델(익명게시판)
class Comment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE, db_column="post_id")

    def __str__(self):
        return self.comment

# 게시글 모델(실명게시판)
class IdPost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

# 댓글 모델(실명게시판)
class IdComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(IdPost, null=True, on_delete=models.CASCADE, db_column="post_id")

    def __str__(self):
        return self.comment

chapter_06/community_project/snsapp/forms.py
from django import forms
from .models import Post, Comment, IdComment, IdPost

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        
        self.fields["title"].widget.attrs = {
            "class":"form-control",
            "placeholder":"글 제목을 입력하세요",
            "rows":20,
        }
        self.fields["body"].widget.attrs = {
            "class":"form-control",
            "placeholder":"글 제목을 입력하세요",
            "rows":20,
            "cols":100,
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.fields["comment"].widget.attrs = {
            "class":"form-control",
            "placeholder":"댓글을 입력하세요",
            "rows":10,
        }




class IdPostForm(forms.ModelForm):
    class Meta:
        model = IdPost
        fields = ["title", "body"]

    def __init__(self, *args, **kwargs):
        super(IdPostForm, self).__init__(*args, **kwargs)
        
        self.fields["title"].widget.attrs = {
            "class":"form-control",
            "placeholder":"글 제목을 입력하세요",
            "rows":20,
        }

        self.fields["body"].widget.attrs = {
            "class":"form-control",
            "placeholder":"글 제목을 입력하세요",
            "rows":20,
            "cols":100,
        }

class IdCommentForm(forms.ModelForm):
    class Meta:
        model = IdComment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(IdCommentForm, self).__init__(*args, **kwargs)

        self.fields["comment"].widget.attrs = {
            "class":"form-control",
            "placeholder":"댓글을 입력하세요",
            "rows":10,
        }

chapter_06/community_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        if user:
            auth.login(request, user)
            return redirect("home")
        else:
            return render(request, "bad.html")
    else:
        return render(request, "login.html")

def logout(request):
    auth.logout(request)
    return redirect("home")

def register(request):
    if request.method == "GET":
        return render(request, "register.html")
    elif request.method == "POST":
        if request.POST["password"] != request.POST["repeatPassword"]:
            return render(request, "register.html")
        else:
            #회원가입
            new_user = User.objects.create_user(username=request.POST["username"], password=request.POST["password"])
            #로그인
            auth.login(request, new_user)
            return redirect("home")

chapter_06/community_project/snsapp/views.py
from xml.etree.ElementTree import Comment
from django.shortcuts import get_object_or_404, render, redirect
from .forms import PostForm, CommentForm, IdPostForm, IdCommentForm
from .models import Post, IdPost
from django.core.paginator import Paginator

def home(request):
    posts = Post.objects.all().order_by("-date")
    paginator = Paginator(posts, 5)
    pagnum = request.GET.get('page')
    posts = paginator.get_page(pagnum)
    return render(request, "index.html", {"posts":posts})

def postcreate(request):
    if request.method == "POST" or request.method=="FILES":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = PostForm()
        return render(request, "post_form.html", {"form":form})

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm()
    return render(request, "detail.html", {"post":post, "comment_form":comment_form})

#save comment
def create_comment(request, post_id):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(Post, pk=post_id)
        finished_form.save()
    return redirect("detail", post_id)



###############################################


def idHome(request):
    posts = IdPost.objects.all().order_by("-date")
    return render(request, "id_index.html", {"posts":posts})

def idPostcreate(request):
    if request.method == "POST" or request.method=="FILES":
        form = IdPostForm(request.POST, request.FILES)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.writer = request.user
            unfinished.save()
            return redirect("idHome")
    else:
        form = IdPostForm()
        return render(request, "id_post_form.html", {"form":form})

def idDetail(request, post_id):
    post = get_object_or_404(IdPost, pk=post_id)
    comment_form = IdCommentForm()
    return render(request, "id_detail.html", {"post":post, "comment_form":comment_form})

#save comment
def new_idComment(request, post_id):
    filled_form = IdCommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(IdPost, pk=post_id)
        finished_form.save()
    return redirect("idDetail", post_id)

chapter_06/community_project/accounts/templates/bad.html
존재하지 않는 회원입니다

<br/>
<a href="{% url 'login' %}">다시 로그인하기</a>

chapter_06/community_project/accounts/templates/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>멋쟁이 사자처럼 -로그인</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-secondary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" action="{% url 'login' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="username" name="username" aria-describedby="emailHelp"
                                                placeholder="Enter Email ID...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="password" name="password" placeholder="Password">
                                        </div>
                                        <button type="submit" class="btn btn-secondary btn-user btn-block">
                                            Login
                                        </button>
                                        <a href="{% provider_login_url 'google' %}" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i>구글 로그인
                                        </a>
                                        <hr>
                                    </form>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'register' %}">회원가입하기</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

chapter_06/community_project/accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>회원가입</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-secondary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user" method="POST" action="{% url 'register' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control form-control-user" id="exampleInputEmail" name="username"
                                        placeholder="Enter Your Id">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user" name="password"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user" name="repeatPassword"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <input type="submit" class="btn btn-secondary btn-user btn-block" value="회원가입하기">
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'login' %}">로그인</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

chapter_06/community_project/snsapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>멋쟁이사자처럼 10기</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
                <div class="sidebar-brand-text mx-3">SKKU_LIKELION <sup>10</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">


            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>익명게시판</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'idHome' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>실명게시판</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        method="GET"
                        action=""
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" name="search" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <input type="submit" class="btn btn-dark">
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-dark" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        
                        <li class="p-3">
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}" class="btn btn-secondary">로그아웃</a>
                            {% else %}
                            <a href="{% url 'login' %}" class="btn btn-secondary">로그인</a>
                            {% endif %}
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if user.is_authenticated %}
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                                {% else %}
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">로그인해주세요</span>
                                {% endif %}
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                {% if not user.is_authenticated %}
                                <a class="dropdown-item" href="">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Login
                                </a>
                                {% else %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                                {% endif %}
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block content %}
                    {% endblock %}
                </div>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-dark" href="">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

chapter_06/community_project/snsapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="border rounded p-1 mb-5">
<h1>{{post.title}}</h1>
<p>{{post.date}}</p>


<p class="mb-5 fs-4">
    {{post.body}}
</p>
</div>
<!--댓글 목록-->

{% for comment in post.comment_set.all %}
    <p>{{comment.comment}}</p>
    <hr>
{% endfor %}


{% if user.is_authenticated %}
<!--댓글 입력-->
<form method="POST" action="{% url 'create_comment' post.id %}">
    {% csrf_token %}
    {{comment_form}}
    <button type="submit" class="btn btn-secondary mt-3">제출</button>
</form>
{% endif %}

{% endblock %}

chapter_06/community_project/snsapp/templates/id_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="border rounded p-1 mb-5">
<h1>{{post.title}}</h1>
<p>{{post.date}}</p>


<p class="mb-5 fs-4">
    {{post.body}}
</p>
</div>
<!--댓글 목록-->

{% for comment in post.idcomment_set.all %}
    <p>{{comment.comment}}</p>
    <hr>
{% endfor %}

{% if user.is_authenticated %}
<!--댓글 입력-->
<form method="POST" action="{% url 'new_idComment' post.id %}">
    {% csrf_token %}
    {{comment_form}}
    <button type="submit" class="btn btn-secondary mt-3">제출</button>
</form>
{% endif %}

{% endblock %}

chapter_06/community_project/snsapp/templates/id_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-dark">실명게시판</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th width="60%">글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tfoot>
                    {% for post in posts %}
                    <tr>
                        <th><a href="{% url 'idDetail' post.id %}">{{post.title}}</a></th>
                        <th>{{post.date}}</th>
                        <th>{{post.writer.username}}</th>
                    </tr>
                    {% endfor %}
                </tfoot>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<a href="{% url 'idPostcreate' %}" class="btn btn-dark btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>
{% endif %}


{% endblock %}

chapter_06/community_project/snsapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-dark">익명게시판</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th width="60%">글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tfoot>
                    {% for post in posts %}
                    <tr>
                        <th><a href="{% url 'detail' post.id %}">{{post.title}}</a></th>
                        <th>{{post.date}}</th>
                        <th>익명</th>
                    </tr>
                    {% endfor %}
                </tfoot>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<a href="{% url 'postcreate' %}" class="btn btn-dark btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>
{% endif %}

<!--pagination-->

{% if posts.has_previous %}
<a href="?page=1">첫 페이지</a>
<a href="?page={{posts.previous_page_number}}">이전 페이지</a>
{% endif %}

<span>{{posts.number}}</span>
<span> / </span>
<span>{{posts.paginator.num_pages}}</span>

{% if posts.has_next %}
<a href="?page={{posts.next_page_number}}">다음 페이지</a>
<a href="?page={{posts.paginator.num_pages}}">마지막 페이지</a>
{% endif %}

{% endblock %}